import { Geist, Jost } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-jost-sans",
  subsets: ["latin"],
});

const jost = Jost({ subsets: ["latin"] });




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
